#!/bin/bash
# Install Strelka on Security Onion
# Author: Wes Lambert, wlambertts@gmail.com

echo "This script will configure a master server and applicable storage nodes to process data from Strelka."
echo
echo "Would you like to continue? [Y/n]"
echo

read startconfig

if [ $startconfig == "Y" ]; then
    :  
else 
    echo "Chose not to continue.  Exiting..."
    exit 0  
fi


# Clone LS config and push to storage node
git clone https://github.com/weslambert/securityonion-strelka.git
cp securityonion-strelka/etc/logstash/* /etc/logstash/custom

# Copy stock Logstash config to /etc/logstash/custom and modify for Strelka
cp /etc/logstash/logstash-template.json /etc/logstash/custom
! grep -q strelka /etc/logstash/custom/logstash-template.json && sed -i 's/]/, "logstash-strelka-*"]/' /etc/logstash/custom/logstash-template.json

echo
echo "Please specify the name of each of your storage node(s), as provided by Salt (separated by a comma)"
salt "*" test.ping
echo
echo "Ex. storagenode1,storagenode2"
echo 
read storagenodes
for i in $(echo $storagenodes | sed "s/,/ /g")
do
    echo $i
    # call Salt cmd.run to mount Strelka template and restart Logstash
    salt "$i" state.highstate
    salt "$i" cmd.run "sed -i 's/^LOGSTASH_OPTIONS=*/LOGSTASH_OPTIONS=\"-v \/etc\/logstash\/logstash-strelka-template.json:\/logstash-strelka-template.json:ro\"/' /etc/nsm/securityonion.conf && so-logstash-restart"
    #salt "$i" cmd.run "so-logstash-restart" 
done

# Specify forward nodes
salt "*" test.ping
read forwardnodes
for i in $(echo $forwardnodes | sed "s/,/ /g")
do
    salt "$i" cmd.run "wget https://raw.githubusercontent.com/weslambert/securityonion-strelka/master/install_strelka_forward && chmod +x install_strelka_forward && ./install_strelka_forward"
done


# Add FW config for sensors
echo
echo "Please specify an IP address for each forward node from which you would like to receive Strelka data (separated by a comma):"
echo
echo "Ex. 192.168.1.4,192.168.1.5"
echo
salt "*" network.ip_addrs
read forwardnodes
for i in $(echo $forwardnodes | sed "s/,/ /g")
do
    ufw_after_rules="-I DOCKER-USER ! -i docker0 -o docker0 -s $i -p tcp --dport 5044 -j ACCEPT"
    sudo iptables $ufw_after_rules
    sed -i "/so-allow/a $ufw_after_rules" /etc/ufw/after.rules    
done
echo
echo "Configuration for master/storage node(s)  is complete!"
echo "Please run ./install_strelka_forward on each forward node"

