#!/bin/bash

. /usr/sbin/so-common

if docker ps | grep -q so-strelka; then
                echo "Already started!"
        else
                docker rm so-strelka >/dev/null 2>&1
	# Start container
	docker run -dit --name=so-strelka -p 5558:5558 -v /etc/strelka/dirstream.yml:/opt/strelka/etc/dirstream/dirstream.yml:ro  -v /nsm/bro/extracted:/nsm/bro/extracted:ro -v /var/log/strelka/:/var/log/strelka/ so-strelka

	# Start server process
	docker exec -dit so-strelka /usr/bin/python3 /opt/strelka/strelka.py

	# Start Dirstream
	docker exec -dit so-strelka /usr/bin/python3 /opt/strelka/strelka_dirstream.py -c /opt/strelka/etc/dirstream/dirstream.yml

fi
